### ISSUE TITLE
Follow up hypothesis failure

### ISSUE THREAD

**Issue by berland** [equinor/pyscal#314]
```
Falsifying example: test_gasoil_krendmax(
    swl=0.0,
    sgcr=1.0000000028043134e-08,
    sorg=0.0,
    sgrononzero=True,
    kroend=0.1,
    kromax=0.1000110100000003,
    krgend=0.1,
    krgmax=0.2,
    h=0.0001,
    fast=False,
)
Traceback (most recent call last):
  File "/home/runner/work/pyscal/pyscal/tests/test_gasoil.py", line 173, in test_gasoil_krendmax
    check_endpoints(gasoil, krgend, krgmax, kroend, kromax)
  File "/home/runner/work/pyscal/pyscal/tests/test_gasoil.py", line 203, in check_endpoints
    assert float_df_checker(gasoil.table, "SG", 0, "KROG", kroend)
AssertionError: assert False
 +  where False = float_df_checker(                 SG      SL           SGN     SON          KROG           KRG\n0      0.000000e+00  1.0000 -1.000000e-0...0  9.998000e-02\n10001  1.000000e+00  0.0000  1.000000e+00  0.0000  0.000000e+00  1.000000e-01\n\n[10002 rows x 6 columns], 'SG', 0, 'KROG', 0.1)
 +    where                  SG      SL           SGN     SON          KROG           KRG\n0      0.000000e+00  1.0000 -1.000000e-0...0  9.998000e-02\n10001  1.000000e+00  0.0000  1.000000e+00  0.0000  0.000000e+00  1.000000e-01\n\n[10002 rows x 6 columns] = <pyscal.gasoil.GasOil object at 0x7f97d46afd30>.table


You can reproduce this example by temporarily adding @reproduce_failure('6.21.6', b'AXicY2CAAY5Py0ygTEa4IM/lO86fGbACAJ2QBMc=') as a decorator on your test case
```

Seen in https://github.com/equinor/pyscal/pull/313

**Comment by berland** [comment]
Already solved in https://github.com/equinor/pyscal/pull/292
