### ISSUE TITLE
UnicodeDecodeError with capillary pressure. Python2 only.

### ISSUE THREAD

**Issue by berland** [equinor/pyscal#95]
This is probably the square symbol in the pc-comment. Triggered when adding simple J to a pc curve. Why not caught in tests??

```
Traceback (most recent call last):
  File "create_relperm_smb.py", line 13, in <module>
    swof_fh.write(wog.SWOF(header=False))
  File "/prog/res/komodo/2020.02.rc3-py27/root/lib/python2.7/site-packages/pyscal/wateroilgas.py", line 91, in SWOF
    return self.wateroil.SWOF(header, dataincommentrow)
  File "/prog/res/komodo/2020.02.rc3-py27/root/lib/python2.7/site-packages/pyscal/wateroil.py", line 985, in SWOF
    string += self.pccomment
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 103: ordinal not in range(128)
```

**Comment by berland** [comment]
Solved in #96 (giving up on fixing, removing non-ascii)
